### PR TITLE
Deep tau v2p5

### PR DESCRIPTION
**Pull request by danielwinterbottom**
- adding new TES and ID SFs for DeepTauv2p5

### CODE REVIEW

**Comment by DennRoy** [comment]
Hi, I notice there's `TauID_SF_dm_DeepTau2018v2p5VSjet_VSjetVVTight_VSeleTight_Jul18.root`, but no `TauID_SF_dm_DeepTau2018v2p5VSjet_VSjetVVTight_VSeleVVLoose_Jul18.root`, is that intentional?

**Comment by danielwinterbottom** [comment]
Hi @DennRoy, We were not planning on releasing a correction for the VVTight as we had issues with the fit for this working point (which was the same situation as we had for v2p1). It was not intentional to include this VVTight ROOT file in the repository so I will remove it now

**Comment by danielwinterbottom** [comment]
@DennRoy The ROOT file will be removed on this PR: https://github.com/cms-tau-pog/TauIDSFs/pull/17. Let me know if you are happy and I will merge it

**Comment by DennRoy** [comment]
Sure, that's good

**Comment by danielwinterbottom** [comment]
ok i merged it

**Pull request merged**
